### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by fregante** [tjx666/github-notifications-preview#1]
Can you set up publishing to the Mozilla Addons store? Once that’s set up and you verify it’s working as a new extension, I can pass you the control of the existing extension: https://addons.mozilla.org/en-US/firefox/addon/notifications-preview-github/

This is easier to implement than the Chrome version and the API is also very easy to get.

**Comment by tjx666** [comment]
My original thought was that my personal version might not be maintained, and I just contribute to the original version: [notifications-preview-github](https://github.com/tanmayrajani/notifications-preview-github) because you can publish it now.

I had migrated all the fixes and new feature by recent prs except the typescript and deps upgrade.

**Comment by fregante** [comment]
If you're interested in the extension, I can give you full control over it as the main maintainer, eventually passing the extensions on each store and the repo. This is why I merged your PRs without making requests on the code.

**Comment by tjx666** [comment]
Ok, I contribute to that extensions if I have anything want to improve.
Will check anything I can do when I have free time.
